In [8]:
import numpy as np

xx = np.linspace(3, 9, 10)
yy = np.linspace(1, 5, 10).T
xx, yy = np.meshgrid(xx, yy)
np.c_[xx.ravel(), yy.ravel()]

array([[3.        , 1.        ],
       [3.66666667, 1.        ],
       [4.33333333, 1.        ],
       [5.        , 1.        ],
       [5.66666667, 1.        ],
       [6.33333333, 1.        ],
       [7.        , 1.        ],
       [7.66666667, 1.        ],
       [8.33333333, 1.        ],
       [9.        , 1.        ],
       [3.        , 1.44444444],
       [3.66666667, 1.44444444],
       [4.33333333, 1.44444444],
       [5.        , 1.44444444],
       [5.66666667, 1.44444444],
       [6.33333333, 1.44444444],
       [7.        , 1.44444444],
       [7.66666667, 1.44444444],
       [8.33333333, 1.44444444],
       [9.        , 1.44444444],
       [3.        , 1.88888889],
       [3.66666667, 1.88888889],
       [4.33333333, 1.88888889],
       [5.        , 1.88888889],
       [5.66666667, 1.88888889],
       [6.33333333, 1.88888889],
       [7.        , 1.88888889],
       [7.66666667, 1.88888889],
       [8.33333333, 1.88888889],
       [9.        , 1.88888889],
       [3.

In [4]:
np.linspace(0, 1, nx)

array([0. , 0.5, 1. ])

In [5]:
np.linspace(0, 1, ny)

array([0., 1.])

In [10]:
import numpy as np
from statsmodels.distributions.empirical_distribution import ECDF
ecdf = ECDF([3, 3, 1, 4])
ecdf([3])

array([0.75])

In [12]:
ecdf = ECDF([1,2,3],[1,2,3])
ecdf([1],[1])

AttributeError: 'list' object has no attribute 'lower'